### ISSUE TITLE
update-notifier-$package.json files still created if NO_UPDATE_NOTIFIER is true

### ISSUE THREAD

**Issue by aheckler** [yeoman/update-notifier#107]
To reproduce:

1. Ensure `~/.config/configstore/` directory is empty.
2. Put `export NO_UPDATE_NOTIFIER=true` in your `.bashrc` or similar.
3. `source ~/.bashrc`
4. `npm update`
5. `~/.config/configstore/update-notifier-npm.json` is created even though I've opted out.

Ran across this situation when the JSON files started showing up in my dotfiles repo. I don't know anything about Node or NPM really, but it seems like the file creation could be skipped in this case?

**Comment by wejendorp** [comment]
I tried squelching the error on a CI server where the user does not have permissions to the `.config` folder by adding the environment variable. No way to avoid the warnings, even though `NO_UPDATE_NOTIFIER` should disable the messages.

**Comment by nexdrew** [comment]
This has been fixed in the 2.2.0 release (tested and verified manually).

Since npm [bundles this dependency](https://github.com/npm/npm/blob/dcc4273cadebe70f853e6d948a425978bc42e045/package.json#L207), this fix won't apply to it until a new version of npm is released (something greater than npm@5.0.3).

@aheckler Thanks for reporting!

@wejendorp Thanks for the fix!

**Comment by nexdrew** [comment]
Looks like this [made it into npm@5.1.0](https://github.com/npm/npm/blob/24ec9f2dd4dcd4f25622dff3a502d4e86a025c0d/package.json#L112). 👍
