### ISSUE TITLE
[FR] Support pnpm

### ISSUE THREAD

**Issue by wenfangdu** [yeoman/update-notifier#231]
Currently, `update-notifier` [only detects npm or yarn](https://github.com/yeoman/update-notifier/blob/3046d0f61a57f8270291b6ab271f8a12df8421a6/update-notifier.js#L141-L150). It is currently using a simple [is-yarn-global](https://github.com/LitoMore/is-yarn-global/blob/main/source/index.ts) package to detect yarn, adding support for pnpm would be nice.

**Comment by sindresorhus** [comment]
I decided to drop the alternative package manager commands. Now it's only npm.

https://github.com/yeoman/update-notifier/commit/a1d8d9d9150d00dbc908820dc3fe8b33bac3003a

**Comment by karlhorky** [comment]
@sindresorhus Hm, why did you drop the alternative package manager commands?

This is actually an incorrect command for a package globally installed by pnpm:

```bash
$ np

...

   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 10.0.5 → 10.0.6    │
   │        Run npm i np to update         │
   │                                       │
   ╰───────────────────────────────────────╯

$ ls -al $(which np)
-rwxr-xr-x  1 k  staff   1.0K Jun 20 17:44 /Users/k/Library/pnpm/np # Global installation in pnpm
```

Also, as [`np`](https://github.com/sindresorhus/np) received pnpm support now, it's a bit of a bumpy experience, when everything else is running with pnpm.

**Comment by sindresorhus** [comment]
It's explained in the commit message.

**Comment by karlhorky** [comment]
Ok thanks, so it's because:

1. Yarn / alternative package manager users should know which commands to run
2. You don't want to maintain the list

Mostly makes sense, although I would take issue with 1., considering many beginners will not have an idea about this, and they will also be using alternative package managers in many companies / projects that they will be a part of.

For 2, if there was a package available that took over maintenance of the commands for all of them, would it be acceptable to revert this change and add pnpm and Bun support? (npm, Yarn, pnpm, Bun)
