### ISSUE TITLE
Running update-notifier from a gulpfile

### ISSUE THREAD

**Issue by vincentmorneau** [yeoman/update-notifier#92]
Hello.

I can't get this working from a gulpfile using the following code:
```javascript
const updateNotifier = require('update-notifier');
const pkg = require('../package.json');

// Checks for available update and returns an instance
const notifier = updateNotifier({
    pkg,
    updateCheckInterval: 1
});

// Notify using the built-in convenience method
notifier.notify({defer: false});
```

More specifically, I added a few console logs in the `UpdateNotifier.prototype.notify` function to see what's going on in there.

```javascript
console.log("!process.stdout.isTTY:", !process.stdout.isTTY);
console.log("isNpm():", isNpm());
console.log("!this.update:", !this.update);
```

And it got me this:

```bash
!process.stdout.isTTY: false
isNpm(): true
!this.update: false
```

The notification message is never getting fired because of [this part](https://github.com/yeoman/update-notifier/blob/master/index.js#L105)

So what is `isNPM()` for and could there be a conflict with Gulp?

- Node version is 4.4.7
- Windows 10
- Trying to implement this module to https://github.com/OraOpenSource/apex-frontend-boost/blob/master/gulpfile.js

**Comment by nexdrew** [comment]
@vincentmorneau The `isNpm()` check determines if the currently executing script (Node process) is being run by npm as an [npm run script](https://docs.npmjs.com/misc/scripts), as I assume [you are using with apex-frontend-boost](https://github.com/OraOpenSource/apex-frontend-boost/blob/v2.1.2/package.json#L26) to run `gulp`.

Typically npm scripts run bin packages that are defined as a local dev dependency in `package.json` of the parent project. In that case, the version of the package is managed as a dependency by npm (and can be monitored/updated by something like [Greenkeeper](https://greenkeeper.io/)). The main use-case of `update-notifier`, however, is for bin packages installed globally (added to the user's `PATH`), where there's no "parent project" keeping track of the version to use, and so baking a "version check" directly into the bin package makes more sense.

So, for example, displaying a notification to a user that says to update `gulp` globally when it's really being used a local dev dependency would just cause confusion (because a local version of the bin takes precedence over the global version when run as an npm script).

Therefore, if `update-notifier` is being executed in the context of an npm script, just no-op.

**Comment by vincentmorneau** [comment]
@nexdrew I understand better now. Thanks for the proper explanation.

Would you say that `update-notifier` is not suited for my needs? My feeling is that I should fork the repo and remove the `isNPM()` part right now.

**Comment by nexdrew** [comment]
@vincentmorneau Based on my perception of how you want folks to use apex-frontend-boost, I would say a better alternative would be to write a [bin file](https://docs.npmjs.com/files/package.json#bin) (using [yargs](http://yargs.js.org/docs/index.html), which you already have as a dependency) that does the `update-notifier` check and wraps/kicks off your gulp script somehow. Then you could direct users to run your bin instead of telling them to run `npm start` (which seems a little awkward to me).

Otherwise, using your own fork of `update-notifier` might not work so well if your main distribution model is not based on installing apex-frontend-boost as a global bin via npm (since that's what `update-notifier` assumes). In other words, you'd have to do your own custom check for updates if `git clone`/`git fetch` is your main install/upgrade path.

**Comment by vincentmorneau** [comment]
@nexdrew Thanks again for taking the time, it's very appreciated. I will definitely head into that direction, as I never liked how `npm start` was invoked either. Closing this issue for now.

**Comment by dnxbf321** [comment]
Thanks a lot, but i want to work with npm script that combines multiple global bins. I will use a fork copy to do the notifier.

**Comment by vincentmorneau** [comment]
@dnxbf321 The following is kind of a hack, but I ended up doing:
```js
delete process.env.npm_config_username;
delete process.env.npm_package_name;
delete process.env.npm_config_heading;

const updateNotifier = require('update-notifier');
const pkg = require('./package.json');

updateNotifier({pkg}).notify();
```

That way I don't need a modified fork of `update-notifier` and I can use it properly in my gulpfile.

**Comment by dnxbf321** [comment]
@vincentmorneau 3Q, it's a better way for me.
